[package]
name = "sima-init"
version = "0.0.1"
edition = "2024"

[dependencies]
platform-info = "2.0.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
shell-words = "1.1.1"
spdlog-rs = "0.5.2"
thiserror = "2.0.18"

